name: 'Home Assistant helper: version-push'
description: 'GitHub action helper: version-push'
inputs:
  key:
    required: true
    default: ''
    description: "JSON key to replace version with, e.g. supervisor, homeassistant.default or hassos[] to replace for all properties in hassos."
  key-description:
    required: false
    description: "Human Friendly description of key which is beeing changed for git commit message."
  version:
    required: true
    default: ''
  channel:
    default: 'dev'
  exclude-list:
    required: false
    default: '[]'
    description: "Exclude specific keys from being updated. Provide a JSON array of keys to exclude."
runs:
  using: "composite"
  steps: 
    - shell: bash
      id: validate-input
      env:
        INPUTS_KEY: ${{ inputs.key }}
        INPUTS_VERSION: ${{ inputs.version }}
        INPUTS_KEY_DESCRIPTION: ${{ inputs.key-description }}
      run: |
        if [[ -z "$INPUTS_KEY" ]];then
          echo "::error::Missing required key 'key' input!"
          exit 1
        elif [[ -z "$INPUTS_VERSION" ]];then
          echo "::error::Missing required key 'version' input!"
          exit 1
        fi
        if [[ -z "$INPUTS_KEY_DESCRIPTION" ]];then
          echo "key-description=$INPUTS_KEY" >> "$GITHUB_OUTPUT"
        else
          echo "key-description=$INPUTS_KEY_DESCRIPTION" >> "$GITHUB_OUTPUT"
        fi

    - shell: bash
      run: git clone --depth 1 https://github.com/jethome-homeassistant/version.git /tmp/version

    - shell: bash
      env:
        INPUTS_KEY: ${{ inputs.key }}
        INPUTS_VERSION: ${{ inputs.version }}
        INPUTS_CHANNEL: ${{ inputs.channel }}
        INPUTS_EXCLUDE_LIST: ${{ inputs['exclude-list'] }}
      run: |
        temp=$(mktemp)
        # Check if exclude list is not empty
        if [[ "$INPUTS_EXCLUDE_LIST" != "[]" ]]; then
          # Strip the [] suffix from INPUTS_KEY
          CLEAN_KEY="${INPUTS_KEY%\[\]}"

          jq --arg key "$CLEAN_KEY" \
            --arg version "$INPUTS_VERSION" \
            --argjson exclude "$INPUTS_EXCLUDE_LIST" '
            .[$key] |= with_entries(
              if (.key | IN($exclude[])) then
                .
              else
                .value = $version
              end
            )
          ' "/tmp/version/$INPUTS_CHANNEL.json" > "${temp}"
        else
          jq ".$INPUTS_KEY |= \"$INPUTS_VERSION\"" "/tmp/version/$INPUTS_CHANNEL.json" > "${temp}"
        fi
        mv "${temp}" "/tmp/version/$INPUTS_CHANNEL.json"

    - shell: bash
      env:
        INPUTS_VERSION: ${{ inputs.version }}
      run: |
        cd /tmp/version
        git commit -am "Bump ${{ steps.validate-input.outputs.key-description }} to $INPUTS_VERSION"
        git push

    - shell: bash
      run: rm -rf /tmp/version